package jwt

import "github.com/golang-jwt/jwt/v4"

//go:generate toolkit gen enum SigningMethod
type SigningMethod uint8

const (
	SIGNING_METHOD_UNKNOWN SigningMethod = iota
	SIGNING_METHOD__ECDSA256
	SIGNING_METHOD__ECDSA384
	SIGNING_METHOD__ECDSA512
	SIGNING_METHOD__HMAC256
	SIGNING_METHOD__HMAC384
	SIGNING_METHOD__HMAC512
	SIGNING_METHOD__RSA256
	SIGNING_METHOD__RSA384
	SIGNING_METHOD__RSA512
	SIGNING_METHOD__RSAPSS256
	SIGNING_METHOD__RSAPSS384
	SIGNING_METHOD__RSAPSS512
)

var SigningMethods = map[SigningMethod]jwt.SigningMethod{
	SIGNING_METHOD_UNKNOWN:    jwt.SigningMethodNone,
	SIGNING_METHOD__ECDSA256:  jwt.SigningMethodES256,
	SIGNING_METHOD__ECDSA384:  jwt.SigningMethodES384,
	SIGNING_METHOD__ECDSA512:  jwt.SigningMethodES512,
	SIGNING_METHOD__HMAC256:   jwt.SigningMethodHS256,
	SIGNING_METHOD__HMAC384:   jwt.SigningMethodHS384,
	SIGNING_METHOD__HMAC512:   jwt.SigningMethodHS512,
	SIGNING_METHOD__RSA256:    jwt.SigningMethodRS256,
	SIGNING_METHOD__RSA384:    jwt.SigningMethodRS384,
	SIGNING_METHOD__RSA512:    jwt.SigningMethodRS512,
	SIGNING_METHOD__RSAPSS256: jwt.SigningMethodPS256,
	SIGNING_METHOD__RSAPSS384: jwt.SigningMethodPS384,
	SIGNING_METHOD__RSAPSS512: jwt.SigningMethodPS512,
}
