DEMO__JWT__ExpIn: 0s
DEMO__JWT__Issuer: ""
DEMO__JWT__Method: ""
DEMO__JWT__SignKey: ""
DEMO__LOG__Format: JSON
DEMO__LOG__Level: debug
DEMO__LOG__Name: srv-demo
DEMO__LOG__Output: ALWAYS
DEMO__LOG__ReportCaller: "false"
DEMO__PGCLI__ConnMaxLifetime: 1h
DEMO__PGCLI__Master: postgres://127.0.0.1:5432
DEMO__PGCLI__PoolSize: "10"
DEMO__PGCLI__Retry_Interval: 3s
DEMO__PGCLI__Retry_Repeats: "3"
DEMO__PGCLI__Slave: ""
DEMO__SERVER__Debug: "true"
DEMO__SERVER__HealthCheck: http://:80/
DEMO__SERVER__Port: "80"
DEMO__SERVER__Spec: ./swagger.json
